[package]
name = "notes-core"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
host-core = { path = "../host-core" }
file-core = { path = "../file-core" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
rusqlite = { workspace = true }
regex = { workspace = true }
walkdir = { workspace = true }
